package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * AssSubowner generated by hbm2java
 */
public class AssSubowner  implements java.io.Serializable {


     private Integer idassSubOwner;
     private Assessment assessment;
     private String assSubOwnerName;
     private String assSubOwnerNic;
     private Integer assSubOwnerStatus;

    public AssSubowner() {
    }

	
    public AssSubowner(Assessment assessment) {
        this.assessment = assessment;
    }
    public AssSubowner(Assessment assessment, String assSubOwnerName, String assSubOwnerNic, Integer assSubOwnerStatus) {
       this.assessment = assessment;
       this.assSubOwnerName = assSubOwnerName;
       this.assSubOwnerNic = assSubOwnerNic;
       this.assSubOwnerStatus = assSubOwnerStatus;
    }
   
    public Integer getIdassSubOwner() {
        return this.idassSubOwner;
    }
    
    public void setIdassSubOwner(Integer idassSubOwner) {
        this.idassSubOwner = idassSubOwner;
    }
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }
    public String getAssSubOwnerName() {
        return this.assSubOwnerName;
    }
    
    public void setAssSubOwnerName(String assSubOwnerName) {
        this.assSubOwnerName = assSubOwnerName;
    }
    public String getAssSubOwnerNic() {
        return this.assSubOwnerNic;
    }
    
    public void setAssSubOwnerNic(String assSubOwnerNic) {
        this.assSubOwnerNic = assSubOwnerNic;
    }
    public Integer getAssSubOwnerStatus() {
        return this.assSubOwnerStatus;
    }
    
    public void setAssSubOwnerStatus(Integer assSubOwnerStatus) {
        this.assSubOwnerStatus = assSubOwnerStatus;
    }




}


