package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * Bank generated by hbm2java
 */
public class Bank  implements java.io.Serializable {


     private Integer idBank;
     private String bankName;

    public Bank() {
    }

    public Bank(String bankName) {
       this.bankName = bankName;
    }
   
    public Integer getIdBank() {
        return this.idBank;
    }
    
    public void setIdBank(Integer idBank) {
        this.idBank = idBank;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }




}


