package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cushasassess generated by hbm2java
 */
public class Cushasassess  implements java.io.Serializable {


     private Integer idCusHasAssess;
     private Assessment assessment;
     private Customer customer;
     private Integer status;
     private Date date;

    public Cushasassess() {
    }

    public Cushasassess(Assessment assessment, Customer customer, Integer status, Date date) {
       this.assessment = assessment;
       this.customer = customer;
       this.status = status;
       this.date = date;
    }
   
    public Integer getIdCusHasAssess() {
        return this.idCusHasAssess;
    }
    
    public void setIdCusHasAssess(Integer idCusHasAssess) {
        this.idCusHasAssess = idCusHasAssess;
    }
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


