package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExCross generated by hbm2java
 */
public class ExCross  implements java.io.Serializable {


     private Integer exCroessDetailId;
     private String exRefno;
     private Double exAmount;
     private Integer exCrossVoteId;
     private Integer exIncomeOrExpence;
     private Integer exActiveStatus;
     private Integer exStatus;
     private Date date;
     private Integer cusId;
     private Integer voucherId;
     private Integer reciptId;
     private Integer isCross;

    public ExCross() {
    }

    public ExCross(String exRefno, Double exAmount, Integer exCrossVoteId, Integer exIncomeOrExpence, Integer exActiveStatus, Integer exStatus, Date date, Integer cusId, Integer voucherId, Integer reciptId, Integer isCross) {
       this.exRefno = exRefno;
       this.exAmount = exAmount;
       this.exCrossVoteId = exCrossVoteId;
       this.exIncomeOrExpence = exIncomeOrExpence;
       this.exActiveStatus = exActiveStatus;
       this.exStatus = exStatus;
       this.date = date;
       this.cusId = cusId;
       this.voucherId = voucherId;
       this.reciptId = reciptId;
       this.isCross = isCross;
    }
   
    public Integer getExCroessDetailId() {
        return this.exCroessDetailId;
    }
    
    public void setExCroessDetailId(Integer exCroessDetailId) {
        this.exCroessDetailId = exCroessDetailId;
    }
    public String getExRefno() {
        return this.exRefno;
    }
    
    public void setExRefno(String exRefno) {
        this.exRefno = exRefno;
    }
    public Double getExAmount() {
        return this.exAmount;
    }
    
    public void setExAmount(Double exAmount) {
        this.exAmount = exAmount;
    }
    public Integer getExCrossVoteId() {
        return this.exCrossVoteId;
    }
    
    public void setExCrossVoteId(Integer exCrossVoteId) {
        this.exCrossVoteId = exCrossVoteId;
    }
    public Integer getExIncomeOrExpence() {
        return this.exIncomeOrExpence;
    }
    
    public void setExIncomeOrExpence(Integer exIncomeOrExpence) {
        this.exIncomeOrExpence = exIncomeOrExpence;
    }
    public Integer getExActiveStatus() {
        return this.exActiveStatus;
    }
    
    public void setExActiveStatus(Integer exActiveStatus) {
        this.exActiveStatus = exActiveStatus;
    }
    public Integer getExStatus() {
        return this.exStatus;
    }
    
    public void setExStatus(Integer exStatus) {
        this.exStatus = exStatus;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getCusId() {
        return this.cusId;
    }
    
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }
    public Integer getVoucherId() {
        return this.voucherId;
    }
    
    public void setVoucherId(Integer voucherId) {
        this.voucherId = voucherId;
    }
    public Integer getReciptId() {
        return this.reciptId;
    }
    
    public void setReciptId(Integer reciptId) {
        this.reciptId = reciptId;
    }
    public Integer getIsCross() {
        return this.isCross;
    }
    
    public void setIsCross(Integer isCross) {
        this.isCross = isCross;
    }




}


