package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1



/**
 * ExDepositCross generated by hbm2java
 */
public class ExDepositCross  implements java.io.Serializable {


     private Integer exDepositApproveId;
     private Integer exDepositReciptId;
     private Integer exApproveStatus;

    public ExDepositCross() {
    }

    public ExDepositCross(Integer exDepositReciptId, Integer exApproveStatus) {
       this.exDepositReciptId = exDepositReciptId;
       this.exApproveStatus = exApproveStatus;
    }
   
    public Integer getExDepositApproveId() {
        return this.exDepositApproveId;
    }
    
    public void setExDepositApproveId(Integer exDepositApproveId) {
        this.exDepositApproveId = exDepositApproveId;
    }
    public Integer getExDepositReciptId() {
        return this.exDepositReciptId;
    }
    
    public void setExDepositReciptId(Integer exDepositReciptId) {
        this.exDepositReciptId = exDepositReciptId;
    }
    public Integer getExApproveStatus() {
        return this.exApproveStatus;
    }
    
    public void setExApproveStatus(Integer exApproveStatus) {
        this.exApproveStatus = exApproveStatus;
    }




}


