package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1



/**
 * ExVoucherRefNoTbl generated by hbm2java
 */
public class ExVoucherRefNoTbl  implements java.io.Serializable {


     private int exVoucherRefNoId;
     private Dipartment dipartment;
     private String exVoucherRefCode;

    public ExVoucherRefNoTbl() {
    }

	
    public ExVoucherRefNoTbl(int exVoucherRefNoId) {
        this.exVoucherRefNoId = exVoucherRefNoId;
    }
    public ExVoucherRefNoTbl(int exVoucherRefNoId, Dipartment dipartment, String exVoucherRefCode) {
       this.exVoucherRefNoId = exVoucherRefNoId;
       this.dipartment = dipartment;
       this.exVoucherRefCode = exVoucherRefCode;
    }
   
    public int getExVoucherRefNoId() {
        return this.exVoucherRefNoId;
    }
    
    public void setExVoucherRefNoId(int exVoucherRefNoId) {
        this.exVoucherRefNoId = exVoucherRefNoId;
    }
    public Dipartment getDipartment() {
        return this.dipartment;
    }
    
    public void setDipartment(Dipartment dipartment) {
        this.dipartment = dipartment;
    }
    public String getExVoucherRefCode() {
        return this.exVoucherRefCode;
    }
    
    public void setExVoucherRefCode(String exVoucherRefCode) {
        this.exVoucherRefCode = exVoucherRefCode;
    }




}


