package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1



/**
 * JobStatus generated by hbm2java
 */
public class JobStatus  implements java.io.Serializable {


     private Integer idJobStatus;
     private String jobstatus;

    public JobStatus() {
    }

    public JobStatus(String jobstatus) {
       this.jobstatus = jobstatus;
    }
   
    public Integer getIdJobStatus() {
        return this.idJobStatus;
    }
    
    public void setIdJobStatus(Integer idJobStatus) {
        this.idJobStatus = idJobStatus;
    }
    public String getJobstatus() {
        return this.jobstatus;
    }
    
    public void setJobstatus(String jobstatus) {
        this.jobstatus = jobstatus;
    }




}


