package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OnlinePay generated by hbm2java
 */
public class OnlinePay  implements java.io.Serializable {


     private Integer idOnPaid;
     private Integer oncusId;
     private Integer appcatId;
     private Integer appId;
     private Date date;
     private Double amount;
     private Integer status;
     private String description;
     private String other;
     private String other2;
     private Integer oder;

    public OnlinePay() {
    }

    public OnlinePay(Integer oncusId, Integer appcatId, Integer appId, Date date, Double amount, Integer status, String description, String other, String other2, Integer oder) {
       this.oncusId = oncusId;
       this.appcatId = appcatId;
       this.appId = appId;
       this.date = date;
       this.amount = amount;
       this.status = status;
       this.description = description;
       this.other = other;
       this.other2 = other2;
       this.oder = oder;
    }
   
    public Integer getIdOnPaid() {
        return this.idOnPaid;
    }
    
    public void setIdOnPaid(Integer idOnPaid) {
        this.idOnPaid = idOnPaid;
    }
    public Integer getOncusId() {
        return this.oncusId;
    }
    
    public void setOncusId(Integer oncusId) {
        this.oncusId = oncusId;
    }
    public Integer getAppcatId() {
        return this.appcatId;
    }
    
    public void setAppcatId(Integer appcatId) {
        this.appcatId = appcatId;
    }
    public Integer getAppId() {
        return this.appId;
    }
    
    public void setAppId(Integer appId) {
        this.appId = appId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    public String getOther2() {
        return this.other2;
    }
    
    public void setOther2(String other2) {
        this.other2 = other2;
    }
    public Integer getOder() {
        return this.oder;
    }
    
    public void setOder(Integer oder) {
        this.oder = oder;
    }




}


