package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OnlineCusprop generated by hbm2java
 */
public class OnlineCusprop  implements java.io.Serializable {


     private Integer idOnCusProp;
     private Integer idOnCus;
     private Integer appCat;
     private Date aplayDate;
     private Integer status;
     private Integer userid;
     private Date approvDate;
     private String propid;
     private String recitid;
     private String description;
     private String ownerName;
     private String other1;
     private String other2;

    public OnlineCusprop() {
    }

    public OnlineCusprop(Integer idOnCus, Integer appCat, Date aplayDate, Integer status, Integer userid, Date approvDate, String propid, String recitid, String description, String ownerName, String other1, String other2) {
       this.idOnCus = idOnCus;
       this.appCat = appCat;
       this.aplayDate = aplayDate;
       this.status = status;
       this.userid = userid;
       this.approvDate = approvDate;
       this.propid = propid;
       this.recitid = recitid;
       this.description = description;
       this.ownerName = ownerName;
       this.other1 = other1;
       this.other2 = other2;
    }
   
    public Integer getIdOnCusProp() {
        return this.idOnCusProp;
    }
    
    public void setIdOnCusProp(Integer idOnCusProp) {
        this.idOnCusProp = idOnCusProp;
    }
    public Integer getIdOnCus() {
        return this.idOnCus;
    }
    
    public void setIdOnCus(Integer idOnCus) {
        this.idOnCus = idOnCus;
    }
    public Integer getAppCat() {
        return this.appCat;
    }
    
    public void setAppCat(Integer appCat) {
        this.appCat = appCat;
    }
    public Date getAplayDate() {
        return this.aplayDate;
    }
    
    public void setAplayDate(Date aplayDate) {
        this.aplayDate = aplayDate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Date getApprovDate() {
        return this.approvDate;
    }
    
    public void setApprovDate(Date approvDate) {
        this.approvDate = approvDate;
    }
    public String getPropid() {
        return this.propid;
    }
    
    public void setPropid(String propid) {
        this.propid = propid;
    }
    public String getRecitid() {
        return this.recitid;
    }
    
    public void setRecitid(String recitid) {
        this.recitid = recitid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public String getOther1() {
        return this.other1;
    }
    
    public void setOther1(String other1) {
        this.other1 = other1;
    }
    public String getOther2() {
        return this.other2;
    }
    
    public void setOther2(String other2) {
        this.other2 = other2;
    }




}


