package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * PersonTitle generated by hbm2java
 */
public class PersonTitle  implements java.io.Serializable {


     private Integer titleId;
     private String titleName;

    public PersonTitle() {
    }

    public PersonTitle(String titleName) {
       this.titleName = titleName;
    }
   
    public Integer getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }




}


