package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * Shoprental generated by hbm2java
 */
public class Shoprental  implements java.io.Serializable {


     private Integer idShopRental;

    public Shoprental() {
    }

   
    public Integer getIdShopRental() {
        return this.idShopRental;
    }
    
    public void setIdShopRental(Integer idShopRental) {
        this.idShopRental = idShopRental;
    }




}


