package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SrShopHasCustomer generated by hbm2java
 */
public class SrShopHasCustomer  implements java.io.Serializable {


     private Integer srShopHasCustomerId;
     private Customer customer;
     private SrShop srShop;
     private Integer srShopHasCustomerStatusActive;
     private Date srShopHasCustomerStartDate;
     private Date srShopHasCustomerEndDate;
     private Double srShopHasCustomerTenderAmount;
     private String srShopHasCustomerDescription;
     private String srShopHasAgreementNo;

    public SrShopHasCustomer() {
    }

    public SrShopHasCustomer(Customer customer, SrShop srShop, Integer srShopHasCustomerStatusActive, Date srShopHasCustomerStartDate, Date srShopHasCustomerEndDate, Double srShopHasCustomerTenderAmount, String srShopHasCustomerDescription, String srShopHasAgreementNo) {
       this.customer = customer;
       this.srShop = srShop;
       this.srShopHasCustomerStatusActive = srShopHasCustomerStatusActive;
       this.srShopHasCustomerStartDate = srShopHasCustomerStartDate;
       this.srShopHasCustomerEndDate = srShopHasCustomerEndDate;
       this.srShopHasCustomerTenderAmount = srShopHasCustomerTenderAmount;
       this.srShopHasCustomerDescription = srShopHasCustomerDescription;
       this.srShopHasAgreementNo = srShopHasAgreementNo;
    }
   
    public Integer getSrShopHasCustomerId() {
        return this.srShopHasCustomerId;
    }
    
    public void setSrShopHasCustomerId(Integer srShopHasCustomerId) {
        this.srShopHasCustomerId = srShopHasCustomerId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public SrShop getSrShop() {
        return this.srShop;
    }
    
    public void setSrShop(SrShop srShop) {
        this.srShop = srShop;
    }
    public Integer getSrShopHasCustomerStatusActive() {
        return this.srShopHasCustomerStatusActive;
    }
    
    public void setSrShopHasCustomerStatusActive(Integer srShopHasCustomerStatusActive) {
        this.srShopHasCustomerStatusActive = srShopHasCustomerStatusActive;
    }
    public Date getSrShopHasCustomerStartDate() {
        return this.srShopHasCustomerStartDate;
    }
    
    public void setSrShopHasCustomerStartDate(Date srShopHasCustomerStartDate) {
        this.srShopHasCustomerStartDate = srShopHasCustomerStartDate;
    }
    public Date getSrShopHasCustomerEndDate() {
        return this.srShopHasCustomerEndDate;
    }
    
    public void setSrShopHasCustomerEndDate(Date srShopHasCustomerEndDate) {
        this.srShopHasCustomerEndDate = srShopHasCustomerEndDate;
    }
    public Double getSrShopHasCustomerTenderAmount() {
        return this.srShopHasCustomerTenderAmount;
    }
    
    public void setSrShopHasCustomerTenderAmount(Double srShopHasCustomerTenderAmount) {
        this.srShopHasCustomerTenderAmount = srShopHasCustomerTenderAmount;
    }
    public String getSrShopHasCustomerDescription() {
        return this.srShopHasCustomerDescription;
    }
    
    public void setSrShopHasCustomerDescription(String srShopHasCustomerDescription) {
        this.srShopHasCustomerDescription = srShopHasCustomerDescription;
    }
    public String getSrShopHasAgreementNo() {
        return this.srShopHasAgreementNo;
    }
    
    public void setSrShopHasAgreementNo(String srShopHasAgreementNo) {
        this.srShopHasAgreementNo = srShopHasAgreementNo;
    }




}


