package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * SrStatus generated by hbm2java
 */
public class SrStatus  implements java.io.Serializable {


     private int srStatusId;
     private String srStatus;

    public SrStatus() {
    }

	
    public SrStatus(int srStatusId) {
        this.srStatusId = srStatusId;
    }
    public SrStatus(int srStatusId, String srStatus) {
       this.srStatusId = srStatusId;
       this.srStatus = srStatus;
    }
   
    public int getSrStatusId() {
        return this.srStatusId;
    }
    
    public void setSrStatusId(int srStatusId) {
        this.srStatusId = srStatusId;
    }
    public String getSrStatus() {
        return this.srStatus;
    }
    
    public void setSrStatus(String srStatus) {
        this.srStatus = srStatus;
    }




}


