package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SwGrade generated by hbm2java
 */
public class SwGrade  implements java.io.Serializable {


     private Integer swGradeId;
     private String swGrade;
     private Set<SwimApp> swimApps = new HashSet<SwimApp>(0);

    public SwGrade() {
    }

    public SwGrade(String swGrade, Set<SwimApp> swimApps) {
       this.swGrade = swGrade;
       this.swimApps = swimApps;
    }
   
    public Integer getSwGradeId() {
        return this.swGradeId;
    }
    
    public void setSwGradeId(Integer swGradeId) {
        this.swGradeId = swGradeId;
    }
    public String getSwGrade() {
        return this.swGrade;
    }
    
    public void setSwGrade(String swGrade) {
        this.swGrade = swGrade;
    }
    public Set<SwimApp> getSwimApps() {
        return this.swimApps;
    }
    
    public void setSwimApps(Set<SwimApp> swimApps) {
        this.swimApps = swimApps;
    }




}


