package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * Tradelicens generated by hbm2java
 */
public class Tradelicens  implements java.io.Serializable {


     private Integer idTradeLicens;

    public Tradelicens() {
    }

   
    public Integer getIdTradeLicens() {
        return this.idTradeLicens;
    }
    
    public void setIdTradeLicens(Integer idTradeLicens) {
        this.idTradeLicens = idTradeLicens;
    }




}


