package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1



/**
 * Watter generated by hbm2java
 */
public class Watter  implements java.io.Serializable {


     private Integer idWatter;

    public Watter() {
    }

   
    public Integer getIdWatter() {
        return this.idWatter;
    }
    
    public void setIdWatter(Integer idWatter) {
        this.idWatter = idWatter;
    }




}


