package pojo;
// Generated Aug 6, 2019 9:53:07 AM by Hibernate Tools 4.3.1



/**
 * WbMDivision generated by hbm2java
 */
public class WbMDivision  implements java.io.Serializable {


     private Integer idivisionId;
     private Street street;
     private String divisonName;

    public WbMDivision() {
    }

	
    public WbMDivision(Street street) {
        this.street = street;
    }
    public WbMDivision(Street street, String divisonName) {
       this.street = street;
       this.divisonName = divisonName;
    }
   
    public Integer getIdivisionId() {
        return this.idivisionId;
    }
    
    public void setIdivisionId(Integer idivisionId) {
        this.idivisionId = idivisionId;
    }
    public Street getStreet() {
        return this.street;
    }
    
    public void setStreet(Street street) {
        this.street = street;
    }
    public String getDivisonName() {
        return this.divisonName;
    }
    
    public void setDivisonName(String divisonName) {
        this.divisonName = divisonName;
    }




}


