package pojo;
// Generated Apr 18, 2020 9:36:49 PM by Hibernate Tools 4.3.1



/**
 * WbMPaidBillStatus generated by hbm2java
 */
public class WbMPaidBillStatus  implements java.io.Serializable {


     private int paidBillStatusId;
     private String paidBillStatus;

    public WbMPaidBillStatus() {
    }

	
    public WbMPaidBillStatus(int paidBillStatusId) {
        this.paidBillStatusId = paidBillStatusId;
    }
    public WbMPaidBillStatus(int paidBillStatusId, String paidBillStatus) {
       this.paidBillStatusId = paidBillStatusId;
       this.paidBillStatus = paidBillStatus;
    }
   
    public int getPaidBillStatusId() {
        return this.paidBillStatusId;
    }
    
    public void setPaidBillStatusId(int paidBillStatusId) {
        this.paidBillStatusId = paidBillStatusId;
    }
    public String getPaidBillStatus() {
        return this.paidBillStatus;
    }
    
    public void setPaidBillStatus(String paidBillStatus) {
        this.paidBillStatus = paidBillStatus;
    }




}


